### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [technoweenie/activesupport_notifications_backport#1]
Hi:
I reckon this is a backport, but I could not find any license in this fine piece of code...
This is likely under the same license as the original? https://github.com/rails/rails/tree/master/activesupport
Otherwise what would it be? Would you mind adding some license?
Thanks!

**Comment by technoweenie** [comment]
Added, thanks for the reminder.  Good luck with your rails upgrade :)

**Comment by pombredanne** [comment]
Thank you my lord!
